### Setup

In [20]:
import pandas as pd
import os
import re
from mistralai.client import Mistral
from rapidfuzz import fuzz, process
from tqdm import tqdm
from dotenv import load_dotenv
import json

In [21]:
load_dotenv(dotenv_path='../.env')

True

In [22]:
client = Mistral(api_key=os.getenv('MISTRAL_API_KEY'))

In [23]:
TEMPLATE_OLD_PATH = "../data/submission_template.csv"
TEMPLATE_PATH = "../data/submission_template_v3.csv"

In [24]:
template_df = pd.read_csv(TEMPLATE_PATH)
template_old_df = pd.read_csv(TEMPLATE_OLD_PATH)
template_df['doc_id'] = template_old_df['doc_id']
template_df

                        id      party_name  votes             doc_id
0      constituency_10_1_1    ประชาธิปัตย์      0  constituency_10_1
1      constituency_10_1_2       ภูมิใจไทย      0  constituency_10_1
2      constituency_10_1_3        เศรษฐกิจ      0  constituency_10_1
3      constituency_10_1_4        กล้าธรรม      0  constituency_10_1
4      constituency_10_1_5           พลวัต      0  constituency_10_1
...                    ...             ...    ...                ...
10048  party_list_34_11_53  ไทยพิทักษ์ธรรม      0   party_list_34_11
10049  party_list_34_11_54    ความหวังใหม่      0   party_list_34_11
10050  party_list_34_11_55       ไทยรวมไทย      0   party_list_34_11
10051  party_list_34_11_56  เพื่อบ้านเมือง      0   party_list_34_11
10052  party_list_34_11_57  พลังไทยรักชาติ      0   party_list_34_11

[10053 rows x 4 columns]

### EDA

In [25]:
template_df['party_name'].unique()

array(['ประชาธิปัตย์', 'ภูมิใจไทย', 'เศรษฐกิจ', 'กล้าธรรม', 'พลวัต',
       'ประชาชน', 'เพื่อไทย', 'ไทยภักดี', 'รวมไทยสร้างชาติ', 'ปวงชนไทย',
       'ไทยสร้างไทย', 'โอกาสใหม่', 'วิชชั่นใหม่', 'ประชาธิปไตยใหม่',
       'รักชาติ', 'ไทยก้าวใหม่', 'ทางเลือกใหม่', 'พลังประชารัฐ',
       'ประชากรไทย', 'ความหวังใหม่', 'อนาคตไทย', 'บ้านเมือง',
       'เพื่อบ้านเมือง', 'ไทยก้าวหน้า', 'รวมไทยสร้าง', 'แรงงานสร้างชาติ',
       'ไทยชนะ', 'พร้อม', 'ไทยพิทักษ์ธรรม', 'ไทยก้าวไทย', 'ไทยก้าวใหม',
       'เสรีรวมไทย', 'เป็นธรรม', 'ไทยธรรม', 'ฟิวชน', 'ฟิวชัน',
       'รวมพลังประชาชน', 'แรงงานสร้างไทย', 'ไทยสร้างชาติ', nan,
       'ปวงชนชาวไทย', 'กลาธรรม', 'สังคมประชาธิปไตยไทย', 'คลองไทย',
       'รวมใจไทย', 'รวมไทยสร้างชา', 'รักษ์ธรรม', 'ชาติ', 'ไทยพร้อม',
       'สร้างชาติ', 'ใหม่', 'พลังสังคมใหม่', 'สร้างอนาคตไทย',
       'ไทยทรัพย์ทวี', 'รวมพลัง', 'ไทรวมพลัง', 'เพื่อชาติไทย', 'มิติใหม่',
       'ท้องที่ไทย', 'พลังเพื่อไทย', 'ก้าวอิสระ', 'เพื่อชีวิตใหม่',
       'ครูไทยเพื่อประชาชน', 'ประชาชาติ', 'พลังธรรมใหม่', 'กรีน',
       'แผ่นดินธรรม', 'ประชาไทย', 'ประชาอาสาชาติ',
       'เครือข่ายชาวนาแห่งประเทศไทย', 'ไทยรวมไทย', 'พลังไทยรักชาติ'],
      dtype=object)

In [26]:
template_df.head()

                    id    party_name  votes             doc_id
0  constituency_10_1_1  ประชาธิปัตย์      0  constituency_10_1
1  constituency_10_1_2     ภูมิใจไทย      0  constituency_10_1
2  constituency_10_1_3      เศรษฐกิจ      0  constituency_10_1
3  constituency_10_1_4      กล้าธรรม      0  constituency_10_1
4  constituency_10_1_5         พลวัต      0  constituency_10_1

In [27]:
NaN_df = template_df[
    template_df['party_name'].isna()
]

NaN_df

                       id party_name  votes             doc_id
737  constituency_14_2_10        NaN      0  constituency_14_2
738  constituency_14_2_11        NaN      0  constituency_14_2
739  constituency_14_2_12        NaN      0  constituency_14_2
740  constituency_14_2_13        NaN      0  constituency_14_2
741  constituency_14_2_14        NaN      0  constituency_14_2
742  constituency_14_2_15        NaN      0  constituency_14_2
743  constituency_14_2_16        NaN      0  constituency_14_2
744  constituency_14_2_17        NaN      0  constituency_14_2

In [28]:
# 737 - 744 Correctly Null
template_df.iloc[737]

id            constituency_14_2_10
party_name                     NaN
votes                            0
doc_id           constituency_14_2
Name: 737, dtype: object

### Extraction

In [29]:
def thai_num_to_int(text: str) -> int:

    thai_to_arabic = str.maketrans("๐๑๒๓๔๕๖๗๘๙", "0123456789")
    text = text.translate(thai_to_arabic)

    # remove non-numeric prefixes
    text = re.sub(r"[^\d,]", " ", text)

    match = re.search(r"[\d,]+", text)
    if not match:
        raise ValueError("No numeric value found")

    return int(match.group().replace(",", ""))

In [30]:
KNOWN_PARTIES = [
    'ประชาธิปัตย์', 'ภูมิใจไทย', 'เศรษฐกิจ', 'กล้าธรรม', 'พลวัต',
    'ประชาชน', 'เพื่อไทย', 'ไทยภักดี', 'รวมไทยสร้างชาติ', 'ปวงชนไทย',
    'ไทยสร้างไทย', 'โอกาสใหม่', 'วิชชั่นใหม่', 'ประชาธิปไตยใหม่',
    'รักชาติ', 'ไทยก้าวใหม่', 'ทางเลือกใหม่', 'พลังประชารัฐ',
    'ประชากรไทย', 'ความหวังใหม่', 'อนาคตไทย', 'บ้านเมือง',
    'เพื่อบ้านเมือง', 'ไทยก้าวหน้า', 'รวมไทยสร้าง', 'แรงงานสร้างชาติ',
    'ไทยชนะ', 'พร้อม', 'ไทยพิทักษ์ธรรม', 'ไทยก้าวไทย', 'ไทยก้าวใหม',
    'เสรีรวมไทย', 'เป็นธรรม', 'ไทยธรรม', 'ฟิวชน', 'ฟิวชัน',
    'รวมพลังประชาชน', 'แรงงานสร้างไทย', 'ไทยสร้างชาติ',
    'ปวงชนชาวไทย', 'กลาธรรม', 'สังคมประชาธิปไตยไทย', 'คลองไทย',
    'รวมใจไทย', 'รวมไทยสร้างชา', 'รักษ์ธรรม', 'ชาติ', 'ไทยพร้อม',
    'สร้างชาติ', 'พลังสังคมใหม่', 'สร้างอนาคตไทย',
    'ไทยทรัพย์ทวี', 'รวมพลัง', 'ไทรวมพลัง', 'เพื่อชาติไทย', 'มิติใหม่',
    'ท้องที่ไทย', 'พลังเพื่อไทย', 'ก้าวอิสระ', 'เพื่อชีวิตใหม่',
    'ครูไทยเพื่อประชาชน', 'ประชาชาติ', 'พลังธรรมใหม่', 'กรีน',
    'แผ่นดินธรรม', 'ประชาไทย', 'ประชาอาสาชาติ',
    'เครือข่ายชาวนาแห่งประเทศไทย', 'ไทยรวมไทย', 'พลังไทยรักชาติ', 'ใหม่'
]

def is_party(text, threshold=70):
    match = process.extractOne(text, KNOWN_PARTIES, scorer=fuzz.ratio)
    return match and match[1] >= threshold

In [31]:
def extract_party_score_dict(md: str) -> dict:
    result = {}

    for line in md.split('\n'):
        if '---' in line or 'รวมคะแนน' in line:
            continue

        parts = [p.strip() for p in line.split('|') if p.strip()]
        if len(parts) < 2:
            continue

        for i, p in enumerate(parts):
            match = process.extractOne(p, KNOWN_PARTIES, scorer=fuzz.ratio)
            if match and match[1] >= 60:
                canonical_party = match[0]
                for vote_raw in reversed(parts[i+1:]):
                    try:
                        vote = thai_num_to_int(vote_raw)
                        result[canonical_party] = vote
                        break
                    except Exception:
                        pass
                break

    return result

In [32]:
def extraction(path):
    try:
        if not os.path.exists(path):
            return {}
        filename = os.path.basename(path)
        with open(path, "rb") as f:
            uploaded = client.files.upload(
                file={"file_name": filename, "content": f},
                purpose="ocr"
            )
        signed_url = client.files.get_signed_url(file_id=uploaded.id)
        result = client.ocr.process(
            model="mistral-ocr-latest",
            document={"type": "document_url", "document_url": signed_url.url}
        )
        # Combine all pages markdown
        #print(result.pages[0].markdown)
        md = "".join(page.markdown for page in result.pages)
        return extract_party_score_dict(md)
    except Exception as e:
        print(e.__str__())
        return {}

### Inference

In [33]:
def assign_votes(df, vote_dict, threshold=60):
    vote_dict = {k: v for k, v in vote_dict.items() if k != 'รวมคะแนนทั้งสิ้น'}
    keys = list(vote_dict.keys())

    def get_vote(party_name):
        if pd.isna(party_name):
            return 0
        match = process.extractOne(
            party_name,
            keys,
            scorer=fuzz.token_set_ratio  # changed from fuzz.ratio
        )
        if match is None:
            return 0
        best_key, score, _ = match
        return vote_dict[best_key] if score >= threshold else 0

    df['votes'] = df['party_name'].apply(get_vote)
    return df

In [34]:
submission_df = template_df.copy()

In [35]:
PREFIX = "../pdf/"

doc_ids = submission_df['doc_id'].unique()

In [36]:
happen = {}

for doc_id in tqdm(doc_ids, desc="Processing", unit="doc"):
	try:
		vote_dict = extraction(PREFIX + doc_id + '.pdf')
		happen[doc_id] = vote_dict
		mask = submission_df["doc_id"] == doc_id
		submission_df.loc[mask] = assign_votes(
			submission_df.loc[mask].copy(),
			vote_dict,
			threshold=60
		)
	except Exception as e:
		print(f"{doc_id}: {str(e)}")

Processing:   0%|          | 0/300 [00:00<?, ?doc/s]

Processing:  76%|███████▋  | 229/300 [28:53<59:45, 50.50s/doc]

API error occurred: Status 520 Content-Type "text/html; charset=UTF-8". Body: <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>

<title>mistral.ai | 520: Web server is returning an unknown error</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />
</head>
<body>
<div id="cf-wrapper">
    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
                <span class="inline-block">Web server is returning an unknown error</span>
                <span class="code-label">Error code 520</span>
            </h1>
            <div>
                Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=api.mistral.ai" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
            </div>
            <div class="mt-3">2026-03-23 13:07:17 UTC</div>
        </header>
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                    <div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Browser

  </h3>

  <span class="leading-1.3 text-2xl text-green-success">Working</span>

</div>
                    <div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&#38;utm_campaign=api.mistral.ai" target="_blank" rel="noopener noreferrer">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    </a>
  </div>
  <span class="md:block w-full truncate">Bangkok</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
  <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=api.mistral.ai" target="_blank" rel="noopener noreferrer">
    Cloudflare
  </a>
  </h3>

  <span class="leading-1.3 text-2xl text-green-success">Working</span>

</div>
                    <div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">api.mistral.ai</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Host

  </h3>

  <span class="leading-1.3 text-2xl text-red-error">Error</span>

</div>
                </div>
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>
                </div>
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>

                <h3 class="text-15 font-semibold mb-2">If you are a visitor of this website:</h3>
                <p class="mb-6">Please try again in a few minutes.</p>

                <h3 class="text-15 font-semibold mb-2">If you are the owner of this website:</h3>
                <p><span>There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a rel="noopener noreferrer" href=   "https://developers.cloudflare.com/support/troubleshooting/http-status-codes/cloudflare-5xx-errors/error-520/">Additional troubleshooting resources</a>.</p>
                </div>
            </div>
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
    <p class="text-13">
      <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">9e0da52b9818732e</strong></span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
      <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
        Your IP:
        <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
        <span class="hidden" id="cf-footer-ip">161.246.147.88</span>
        <span class="cf-footer-separator sm:hidden">&bull;</span>
      </span>
      <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&#38;utm_campaign=api.mistral.ai" id="brand_link" target="_blank">Cloudflare</a></span>

    </p>
    <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
  </div><!-- /.error-footer -->

    </div>
</div>
</body>
</html>

Processing: 100%|██████████| 300/300 [40:38<00:00,  8.13s/doc]

In [37]:
with open("../anormaly/party_list_10_24.json") as f:
    data = json.load(f)

for item in data:
    party = item["สังกัดพรรคการเมือง"].strip()
    vote_raw = item["คะแนน"].strip()
    try:
        vote = thai_num_to_int(vote_raw)
        match = process.extractOne(party, KNOWN_PARTIES, scorer=fuzz.ratio)
        if match and match[1] >= 60:
            canonical = match[0]
            mask = (submission_df["doc_id"] == "party_list_10_24") & (submission_df["party_name"] == canonical)
            submission_df.loc[mask, "votes"] = vote
    except Exception as e:
        print(f"Error: {party} - {e}")

In [38]:
submission_df

                        id      party_name  votes             doc_id
0      constituency_10_1_1    ประชาธิปัตย์  14813  constituency_10_1
1      constituency_10_1_2       ภูมิใจไทย  14368  constituency_10_1
2      constituency_10_1_3        เศรษฐกิจ    979  constituency_10_1
3      constituency_10_1_4        กล้าธรรม    244  constituency_10_1
4      constituency_10_1_5           พลวัต    351  constituency_10_1
...                    ...             ...    ...                ...
10048  party_list_34_11_53  ไทยพิทักษ์ธรรม     14   party_list_34_11
10049  party_list_34_11_54    ความหวังใหม่     41   party_list_34_11
10050  party_list_34_11_55       ไทยรวมไทย     29   party_list_34_11
10051  party_list_34_11_56  เพื่อบ้านเมือง     41   party_list_34_11
10052  party_list_34_11_57  พลังไทยรักชาติ     71   party_list_34_11

[10053 rows x 4 columns]

In [39]:
for key, values in happen.items():
	if values == {}:
		print(key)

party_list_10_24
party_list_20_4

In [44]:
output_df = submission_df.drop(['doc_id', 'party_name'], axis=1)

In [45]:
output_df

                        id  votes
0      constituency_10_1_1  14813
1      constituency_10_1_2  14368
2      constituency_10_1_3    979
3      constituency_10_1_4    244
4      constituency_10_1_5    351
...                    ...    ...
10048  party_list_34_11_53     14
10049  party_list_34_11_54     41
10050  party_list_34_11_55     29
10051  party_list_34_11_56     41
10052  party_list_34_11_57     71

[10053 rows x 2 columns]

In [46]:
output_df.to_csv("submission4.csv", index=False)